// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmailReply_Status int32

const (
	EmailReply_Unknown EmailReply_Status = 0
	EmailReply_Success EmailReply_Status = 1
	EmailReply_Fail    EmailReply_Status = 2
)

var EmailReply_Status_name = map[int32]string{
	0: "Unknown",
	1: "Success",
	2: "Fail",
}

var EmailReply_Status_value = map[string]int32{
	"Unknown": 0,
	"Success": 1,
	"Fail":    2,
}

func (x EmailReply_Status) String() string {
	return proto.EnumName(EmailReply_Status_name, int32(x))
}

func (EmailReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1, 0}
}

// The request message containing the user's name.
type EmailRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []string `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc                   []string `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc                  []string `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Html                 string   `protobuf:"bytes,6,opt,name=html,proto3" json:"html,omitempty"`
	Filename             []string `protobuf:"bytes,7,rep,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (m *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(m, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EmailRequest) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *EmailRequest) GetCc() []string {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *EmailRequest) GetBcc() []string {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func (m *EmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailRequest) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

func (m *EmailRequest) GetFilename() []string {
	if m != nil {
		return m.Filename
	}
	return nil
}

// The response message containing the greetings
type EmailReply struct {
	Status               EmailReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.EmailReply_Status" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EmailReply) Reset()         { *m = EmailReply{} }
func (m *EmailReply) String() string { return proto.CompactTextString(m) }
func (*EmailReply) ProtoMessage()    {}
func (*EmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *EmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailReply.Unmarshal(m, b)
}
func (m *EmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailReply.Marshal(b, m, deterministic)
}
func (m *EmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailReply.Merge(m, src)
}
func (m *EmailReply) XXX_Size() int {
	return xxx_messageInfo_EmailReply.Size(m)
}
func (m *EmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmailReply proto.InternalMessageInfo

func (m *EmailReply) GetStatus() EmailReply_Status {
	if m != nil {
		return m.Status
	}
	return EmailReply_Unknown
}

func (m *EmailReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.EmailReply_Status", EmailReply_Status_name, EmailReply_Status_value)
	proto.RegisterType((*EmailRequest)(nil), "pb.EmailRequest")
	proto.RegisterType((*EmailReply)(nil), "pb.EmailReply")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4e, 0x84, 0x30,
	0x10, 0xc6, 0x97, 0x82, 0xb0, 0xcc, 0x1a, 0xd2, 0x4c, 0x62, 0xd2, 0xec, 0x69, 0xc3, 0x69, 0x0f,
	0x8a, 0xc9, 0x7a, 0xf7, 0xa6, 0x37, 0x2f, 0x10, 0x1f, 0x00, 0xba, 0x5d, 0x17, 0x2d, 0x14, 0x69,
	0xc9, 0xc6, 0xb3, 0xef, 0xe1, 0xb3, 0x9a, 0xb6, 0xf8, 0x67, 0x6f, 0xdf, 0x8f, 0x19, 0xbe, 0xfe,
	0x32, 0x40, 0x8f, 0x42, 0x4a, 0x75, 0x52, 0xa3, 0xdc, 0x17, 0xc3, 0xa8, 0x8c, 0x42, 0x32, 0x34,
	0xf9, 0x57, 0x00, 0x97, 0x0f, 0x5d, 0xdd, 0xca, 0x52, 0xbc, 0x4f, 0x42, 0x1b, 0x44, 0x88, 0x0e,
	0xa3, 0xea, 0x58, 0xb0, 0x09, 0xb6, 0x69, 0xe9, 0x32, 0x66, 0x40, 0x8c, 0x62, 0x64, 0x13, 0x6e,
	0xd3, 0x92, 0x18, 0x65, 0x99, 0x73, 0x16, 0x7a, 0xe6, 0x1c, 0x29, 0x84, 0x0d, 0xe7, 0x2c, 0x72,
	0x1f, 0x6c, 0x44, 0x06, 0x89, 0x9e, 0x9a, 0x57, 0xc1, 0x0d, 0xbb, 0x70, 0x45, 0x3f, 0x68, 0xfb,
	0x8f, 0xa6, 0x93, 0x2c, 0xf6, 0xfd, 0x36, 0xe3, 0x1a, 0x96, 0x87, 0x56, 0x8a, 0xbe, 0xee, 0x04,
	0x4b, 0x5c, 0xc9, 0x2f, 0xe7, 0x9f, 0x01, 0xc0, 0x2c, 0x38, 0xc8, 0x0f, 0xbc, 0x81, 0x58, 0x9b,
	0xda, 0x4c, 0xda, 0x09, 0x66, 0xbb, 0xab, 0x62, 0x68, 0x8a, 0xbf, 0x79, 0x51, 0xb9, 0x61, 0x39,
	0x2f, 0x59, 0x8f, 0x4e, 0x68, 0x5d, 0xbf, 0x08, 0x46, 0xbc, 0xc7, 0x8c, 0xf9, 0x35, 0xc4, 0x7e,
	0x17, 0x57, 0x90, 0x3c, 0xf7, 0x6f, 0xbd, 0x3a, 0xf5, 0x74, 0x61, 0xa1, 0x9a, 0x38, 0x17, 0x5a,
	0xd3, 0x00, 0x97, 0x10, 0x3d, 0xd6, 0xad, 0xa4, 0x64, 0x77, 0x0f, 0xab, 0x4a, 0xf4, 0xfb, 0x27,
	0xff, 0x33, 0xde, 0x42, 0x6a, 0xd1, 0xbd, 0x8b, 0xf4, 0x9f, 0x82, 0xbb, 0xe1, 0x3a, 0x3b, 0x97,
	0xca, 0x17, 0x4d, 0xec, 0x2e, 0x7e, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x20, 0xb0, 0x7d, 0xcd,
	0x85, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SendMessageClient is the client API for SendMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendMessageClient interface {
	// Sends a greeting
	SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailReply, error)
}

type sendMessageClient struct {
	cc *grpc.ClientConn
}

func NewSendMessageClient(cc *grpc.ClientConn) SendMessageClient {
	return &sendMessageClient{cc}
}

func (c *sendMessageClient) SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailReply, error) {
	out := new(EmailReply)
	err := c.cc.Invoke(ctx, "/pb.SendMessage/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendMessageServer is the server API for SendMessage service.
type SendMessageServer interface {
	// Sends a greeting
	SendEmail(context.Context, *EmailRequest) (*EmailReply, error)
}

// UnimplementedSendMessageServer can be embedded to have forward compatible implementations.
type UnimplementedSendMessageServer struct {
}

func (*UnimplementedSendMessageServer) SendEmail(ctx context.Context, req *EmailRequest) (*EmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}

func RegisterSendMessageServer(s *grpc.Server, srv SendMessageServer) {
	s.RegisterService(&_SendMessage_serviceDesc, srv)
}

func _SendMessage_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMessageServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SendMessage/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMessageServer).SendEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendMessage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SendMessage",
	HandlerType: (*SendMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _SendMessage_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
