// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmailReply_Status int32

const (
	EmailReply_Unknown EmailReply_Status = 0
	EmailReply_Success EmailReply_Status = 1
	EmailReply_Fail    EmailReply_Status = 2
)

var EmailReply_Status_name = map[int32]string{
	0: "Unknown",
	1: "Success",
	2: "Fail",
}

var EmailReply_Status_value = map[string]int32{
	"Unknown": 0,
	"Success": 1,
	"Fail":    2,
}

func (x EmailReply_Status) String() string {
	return proto.EnumName(EmailReply_Status_name, int32(x))
}

func (EmailReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2, 0}
}

type CodeReply_Status int32

const (
	CodeReply_Unknown CodeReply_Status = 0
	CodeReply_Success CodeReply_Status = 1
	CodeReply_Fail    CodeReply_Status = 2
)

var CodeReply_Status_name = map[int32]string{
	0: "Unknown",
	1: "Success",
	2: "Fail",
}

var CodeReply_Status_value = map[string]int32{
	"Unknown": 0,
	"Success": 1,
	"Fail":    2,
}

func (x CodeReply_Status) String() string {
	return proto.EnumName(CodeReply_Status_name, int32(x))
}

func (CodeReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3, 0}
}

// The request message containing email message.
type EmailRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []string `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc                   []string `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc                  []string `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Html                 string   `protobuf:"bytes,6,opt,name=html,proto3" json:"html,omitempty"`
	Filename             []string `protobuf:"bytes,7,rep,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (m *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(m, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EmailRequest) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *EmailRequest) GetCc() []string {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *EmailRequest) GetBcc() []string {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func (m *EmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailRequest) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

func (m *EmailRequest) GetFilename() []string {
	if m != nil {
		return m.Filename
	}
	return nil
}

// The request message containing code message.
type CodeRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []string `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeRequest) Reset()         { *m = CodeRequest{} }
func (m *CodeRequest) String() string { return proto.CompactTextString(m) }
func (*CodeRequest) ProtoMessage()    {}
func (*CodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *CodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeRequest.Unmarshal(m, b)
}
func (m *CodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeRequest.Marshal(b, m, deterministic)
}
func (m *CodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeRequest.Merge(m, src)
}
func (m *CodeRequest) XXX_Size() int {
	return xxx_messageInfo_CodeRequest.Size(m)
}
func (m *CodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CodeRequest proto.InternalMessageInfo

func (m *CodeRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *CodeRequest) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *CodeRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The response message containing the sendmessage
type EmailReply struct {
	Status               EmailReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.EmailReply_Status" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EmailReply) Reset()         { *m = EmailReply{} }
func (m *EmailReply) String() string { return proto.CompactTextString(m) }
func (*EmailReply) ProtoMessage()    {}
func (*EmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *EmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailReply.Unmarshal(m, b)
}
func (m *EmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailReply.Marshal(b, m, deterministic)
}
func (m *EmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailReply.Merge(m, src)
}
func (m *EmailReply) XXX_Size() int {
	return xxx_messageInfo_EmailReply.Size(m)
}
func (m *EmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmailReply proto.InternalMessageInfo

func (m *EmailReply) GetStatus() EmailReply_Status {
	if m != nil {
		return m.Status
	}
	return EmailReply_Unknown
}

func (m *EmailReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The response message containing the sendcode
type CodeReply struct {
	Status               CodeReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.CodeReply_Status" json:"status,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CodeReply) Reset()         { *m = CodeReply{} }
func (m *CodeReply) String() string { return proto.CompactTextString(m) }
func (*CodeReply) ProtoMessage()    {}
func (*CodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *CodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeReply.Unmarshal(m, b)
}
func (m *CodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeReply.Marshal(b, m, deterministic)
}
func (m *CodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeReply.Merge(m, src)
}
func (m *CodeReply) XXX_Size() int {
	return xxx_messageInfo_CodeReply.Size(m)
}
func (m *CodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_CodeReply proto.InternalMessageInfo

func (m *CodeReply) GetStatus() CodeReply_Status {
	if m != nil {
		return m.Status
	}
	return CodeReply_Unknown
}

func (m *CodeReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.EmailReply_Status", EmailReply_Status_name, EmailReply_Status_value)
	proto.RegisterEnum("pb.CodeReply_Status", CodeReply_Status_name, CodeReply_Status_value)
	proto.RegisterType((*EmailRequest)(nil), "pb.EmailRequest")
	proto.RegisterType((*CodeRequest)(nil), "pb.CodeRequest")
	proto.RegisterType((*EmailReply)(nil), "pb.EmailReply")
	proto.RegisterType((*CodeReply)(nil), "pb.CodeReply")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x1b, 0xa7, 0x24, 0xcd, 0x95, 0x96, 0xe8, 0x04, 0x92, 0xd5, 0xa9, 0xf2, 0xd4, 0xa1,
	0x04, 0xa9, 0x3c, 0x02, 0x82, 0x05, 0xb1, 0xa4, 0xe2, 0x01, 0x12, 0xd7, 0xa5, 0x85, 0x24, 0x0e,
	0xb5, 0x23, 0xc4, 0x88, 0x78, 0x0f, 0x9e, 0x15, 0xd9, 0x0e, 0x6d, 0xc3, 0xc6, 0xc0, 0x76, 0x7f,
	0xee, 0xee, 0xcf, 0xf7, 0x9f, 0x0c, 0xa3, 0x52, 0x28, 0x95, 0x3d, 0x89, 0xa4, 0xde, 0x49, 0x2d,
	0x91, 0xd4, 0x39, 0xfb, 0xf2, 0xe0, 0xf4, 0xb6, 0xcc, 0xb6, 0x45, 0x2a, 0x5e, 0x1b, 0xa1, 0x34,
	0x22, 0xf4, 0xd7, 0x3b, 0x59, 0x52, 0x6f, 0xea, 0xcd, 0xa2, 0xd4, 0xd6, 0x38, 0x06, 0xa2, 0x25,
	0x25, 0x53, 0x7f, 0x16, 0xa5, 0x44, 0x4b, 0xa3, 0x39, 0xa7, 0xbe, 0xd3, 0x9c, 0x63, 0x0c, 0x7e,
	0xce, 0x39, 0xed, 0xdb, 0x0f, 0xa6, 0x44, 0x0a, 0xa1, 0x6a, 0xf2, 0x67, 0xc1, 0x35, 0x3d, 0xb1,
	0x46, 0x3f, 0xd2, 0xf8, 0x6f, 0x74, 0x59, 0xd0, 0xc0, 0xf9, 0x9b, 0x1a, 0x27, 0x30, 0x58, 0x6f,
	0x0b, 0x51, 0x65, 0xa5, 0xa0, 0xa1, 0x35, 0xd9, 0x6b, 0x76, 0x0f, 0xc3, 0x1b, 0xb9, 0x12, 0x7f,
	0xc1, 0xa3, 0x10, 0xb6, 0x41, 0xa9, 0xef, 0x7e, 0xde, 0x4a, 0xf6, 0xe9, 0x01, 0xb4, 0x69, 0xeb,
	0xe2, 0x1d, 0x2f, 0x21, 0x50, 0x3a, 0xd3, 0x8d, 0xb2, 0x76, 0xe3, 0xc5, 0x45, 0x52, 0xe7, 0xc9,
	0xa1, 0x9f, 0x2c, 0x6d, 0x33, 0x6d, 0x87, 0x8e, 0x7d, 0x49, 0xd7, 0x77, 0x0e, 0x81, 0x9b, 0xc5,
	0x21, 0x84, 0x8f, 0xd5, 0x4b, 0x25, 0xdf, 0xaa, 0xb8, 0x67, 0xc4, 0xb2, 0xe1, 0x5c, 0x28, 0x15,
	0x7b, 0x38, 0x80, 0xfe, 0x5d, 0xb6, 0x2d, 0x62, 0xc2, 0x3e, 0x3c, 0x88, 0x5c, 0x26, 0x03, 0x31,
	0xff, 0x05, 0x71, 0x6e, 0x20, 0xf6, 0xed, 0x7f, 0x62, 0x58, 0x6c, 0x20, 0x7c, 0x70, 0x8b, 0x78,
	0x05, 0xd1, 0x52, 0x54, 0x2b, 0x9b, 0x1b, 0xe3, 0xa3, 0x13, 0xd8, 0x8b, 0x4f, 0xc6, 0xdd, 0xa3,
	0xb0, 0x1e, 0xce, 0x61, 0x60, 0x16, 0x0c, 0x23, 0x9e, 0x1d, 0x68, 0xdd, 0xf8, 0xa8, 0x83, 0xcf,
	0x7a, 0x79, 0x60, 0x1f, 0xdb, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0x42, 0x39, 0x80,
	0x7d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageClient interface {
	// Sends a greeting
	SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailReply, error)
	SendCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeReply, error)
}

type messageClient struct {
	cc *grpc.ClientConn
}

func NewMessageClient(cc *grpc.ClientConn) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailReply, error) {
	out := new(EmailReply)
	err := c.cc.Invoke(ctx, "/pb.Message/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SendCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeReply, error) {
	out := new(CodeReply)
	err := c.cc.Invoke(ctx, "/pb.Message/SendCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
type MessageServer interface {
	// Sends a greeting
	SendEmail(context.Context, *EmailRequest) (*EmailReply, error)
	SendCode(context.Context, *CodeRequest) (*CodeReply, error)
}

// UnimplementedMessageServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (*UnimplementedMessageServer) SendEmail(ctx context.Context, req *EmailRequest) (*EmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (*UnimplementedMessageServer) SendCode(ctx context.Context, req *CodeRequest) (*CodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCode not implemented")
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/SendCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendCode(ctx, req.(*CodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _Message_SendEmail_Handler,
		},
		{
			MethodName: "SendCode",
			Handler:    _Message_SendCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
