// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sendmessage.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmailReply_Status int32

const (
	EmailReply_Unknown EmailReply_Status = 0
	EmailReply_Success EmailReply_Status = 1
	EmailReply_Fail    EmailReply_Status = 2
)

var EmailReply_Status_name = map[int32]string{
	0: "Unknown",
	1: "Success",
	2: "Fail",
}

var EmailReply_Status_value = map[string]int32{
	"Unknown": 0,
	"Success": 1,
	"Fail":    2,
}

func (x EmailReply_Status) String() string {
	return proto.EnumName(EmailReply_Status_name, int32(x))
}

func (EmailReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb71e5b3da85faee, []int{2, 0}
}

type CodeReply_Status int32

const (
	CodeReply_Unknown CodeReply_Status = 0
	CodeReply_Success CodeReply_Status = 1
	CodeReply_Fail    CodeReply_Status = 2
)

var CodeReply_Status_name = map[int32]string{
	0: "Unknown",
	1: "Success",
	2: "Fail",
}

var CodeReply_Status_value = map[string]int32{
	"Unknown": 0,
	"Success": 1,
	"Fail":    2,
}

func (x CodeReply_Status) String() string {
	return proto.EnumName(CodeReply_Status_name, int32(x))
}

func (CodeReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb71e5b3da85faee, []int{3, 0}
}

// The request message containing email message.
type EmailRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []string `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc                   []string `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc                  []string `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Html                 string   `protobuf:"bytes,6,opt,name=html,proto3" json:"html,omitempty"`
	Filename             []string `protobuf:"bytes,7,rep,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb71e5b3da85faee, []int{0}
}

func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (m *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(m, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EmailRequest) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *EmailRequest) GetCc() []string {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *EmailRequest) GetBcc() []string {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func (m *EmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailRequest) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

func (m *EmailRequest) GetFilename() []string {
	if m != nil {
		return m.Filename
	}
	return nil
}

// The request message containing code message.
type CodeRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []string `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeRequest) Reset()         { *m = CodeRequest{} }
func (m *CodeRequest) String() string { return proto.CompactTextString(m) }
func (*CodeRequest) ProtoMessage()    {}
func (*CodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb71e5b3da85faee, []int{1}
}

func (m *CodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeRequest.Unmarshal(m, b)
}
func (m *CodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeRequest.Marshal(b, m, deterministic)
}
func (m *CodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeRequest.Merge(m, src)
}
func (m *CodeRequest) XXX_Size() int {
	return xxx_messageInfo_CodeRequest.Size(m)
}
func (m *CodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CodeRequest proto.InternalMessageInfo

func (m *CodeRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *CodeRequest) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *CodeRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The response message containing the sendmessage
type EmailReply struct {
	Status               EmailReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.EmailReply_Status" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EmailReply) Reset()         { *m = EmailReply{} }
func (m *EmailReply) String() string { return proto.CompactTextString(m) }
func (*EmailReply) ProtoMessage()    {}
func (*EmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb71e5b3da85faee, []int{2}
}

func (m *EmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailReply.Unmarshal(m, b)
}
func (m *EmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailReply.Marshal(b, m, deterministic)
}
func (m *EmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailReply.Merge(m, src)
}
func (m *EmailReply) XXX_Size() int {
	return xxx_messageInfo_EmailReply.Size(m)
}
func (m *EmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmailReply proto.InternalMessageInfo

func (m *EmailReply) GetStatus() EmailReply_Status {
	if m != nil {
		return m.Status
	}
	return EmailReply_Unknown
}

func (m *EmailReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The response message containing the sendcode
type CodeReply struct {
	Status               CodeReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.CodeReply_Status" json:"status,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CodeReply) Reset()         { *m = CodeReply{} }
func (m *CodeReply) String() string { return proto.CompactTextString(m) }
func (*CodeReply) ProtoMessage()    {}
func (*CodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb71e5b3da85faee, []int{3}
}

func (m *CodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeReply.Unmarshal(m, b)
}
func (m *CodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeReply.Marshal(b, m, deterministic)
}
func (m *CodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeReply.Merge(m, src)
}
func (m *CodeReply) XXX_Size() int {
	return xxx_messageInfo_CodeReply.Size(m)
}
func (m *CodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_CodeReply proto.InternalMessageInfo

func (m *CodeReply) GetStatus() CodeReply_Status {
	if m != nil {
		return m.Status
	}
	return CodeReply_Unknown
}

func (m *CodeReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.EmailReply_Status", EmailReply_Status_name, EmailReply_Status_value)
	proto.RegisterEnum("pb.CodeReply_Status", CodeReply_Status_name, CodeReply_Status_value)
	proto.RegisterType((*EmailRequest)(nil), "pb.EmailRequest")
	proto.RegisterType((*CodeRequest)(nil), "pb.CodeRequest")
	proto.RegisterType((*EmailReply)(nil), "pb.EmailReply")
	proto.RegisterType((*CodeReply)(nil), "pb.CodeReply")
}

func init() { proto.RegisterFile("sendmessage.proto", fileDescriptor_bb71e5b3da85faee) }

var fileDescriptor_bb71e5b3da85faee = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x4f, 0x4e, 0xf3, 0x30,
	0x10, 0xc5, 0x9b, 0xa4, 0x5f, 0xd2, 0x4c, 0x3f, 0x4a, 0x18, 0x81, 0x64, 0x75, 0x55, 0x79, 0xd5,
	0x45, 0x09, 0x52, 0x39, 0x02, 0x82, 0x0d, 0x62, 0x93, 0x8a, 0x03, 0x24, 0xae, 0x0b, 0x05, 0xc7,
	0x0e, 0xb5, 0x23, 0xc4, 0x12, 0x71, 0x0f, 0xce, 0x8a, 0x6c, 0x87, 0xfe, 0x61, 0xc7, 0x82, 0xdd,
	0xbc, 0xcc, 0xcc, 0xcb, 0xef, 0x8d, 0x0c, 0x27, 0x9a, 0xcb, 0x65, 0xcd, 0xb5, 0x2e, 0x1f, 0x78,
	0xde, 0x6c, 0x94, 0x51, 0x18, 0x36, 0x15, 0xfd, 0x0c, 0xe0, 0xff, 0x75, 0x5d, 0xae, 0x45, 0xc1,
	0x5f, 0x5a, 0xae, 0x0d, 0x22, 0xf4, 0x57, 0x1b, 0x55, 0x93, 0x60, 0x12, 0x4c, 0xd3, 0xc2, 0xd5,
	0x38, 0x82, 0xd0, 0x28, 0x12, 0x4e, 0xa2, 0x69, 0x5a, 0x84, 0x46, 0x59, 0xcd, 0x18, 0x89, 0xbc,
	0x66, 0x0c, 0x33, 0x88, 0x2a, 0xc6, 0x48, 0xdf, 0x7d, 0xb0, 0x25, 0x12, 0x48, 0x74, 0x5b, 0x3d,
	0x71, 0x66, 0xc8, 0x3f, 0x67, 0xf4, 0x2d, 0xad, 0xff, 0xa3, 0xa9, 0x05, 0x89, 0xbd, 0xbf, 0xad,
	0x71, 0x0c, 0x83, 0xd5, 0x5a, 0x70, 0x59, 0xd6, 0x9c, 0x24, 0xce, 0x64, 0xab, 0xe9, 0x2d, 0x0c,
	0xaf, 0xd4, 0x92, 0xff, 0x06, 0x8f, 0x40, 0xd2, 0x05, 0x25, 0x91, 0xff, 0x79, 0x27, 0xe9, 0x47,
	0x00, 0xd0, 0xa5, 0x6d, 0xc4, 0x1b, 0x9e, 0x43, 0xac, 0x4d, 0x69, 0x5a, 0xed, 0xec, 0x46, 0xf3,
	0xb3, 0xbc, 0xa9, 0xf2, 0x5d, 0x3f, 0x5f, 0xb8, 0x66, 0xd1, 0x0d, 0xed, 0xfb, 0x86, 0x87, 0xbe,
	0x33, 0x88, 0xfd, 0x2c, 0x0e, 0x21, 0xb9, 0x97, 0xcf, 0x52, 0xbd, 0xca, 0xac, 0x67, 0xc5, 0xa2,
	0x65, 0x8c, 0x6b, 0x9d, 0x05, 0x38, 0x80, 0xfe, 0x4d, 0xb9, 0x16, 0x59, 0x48, 0xdf, 0x03, 0x48,
	0x7d, 0x26, 0x0b, 0x31, 0xfb, 0x01, 0x71, 0x6a, 0x21, 0xb6, 0xed, 0x3f, 0x62, 0x98, 0x0b, 0x18,
	0x2e, 0xb8, 0x5c, 0xde, 0xf9, 0x65, 0xbc, 0x80, 0xd4, 0x4a, 0x97, 0x1d, 0xb3, 0xbd, 0x33, 0xb8,
	0xab, 0x8f, 0x47, 0x87, 0x87, 0xa1, 0x3d, 0x9c, 0xc1, 0xc0, 0x2e, 0x58, 0x4e, 0x3c, 0xde, 0x11,
	0xfb, 0xf1, 0xa3, 0x83, 0x08, 0xb4, 0x57, 0xc5, 0xee, 0xc1, 0x5d, 0x7e, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xce, 0xef, 0xe9, 0xfa, 0x85, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SendMessageClient is the client API for SendMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendMessageClient interface {
	// Sends a greeting
	SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailReply, error)
	SendCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeReply, error)
}

type sendMessageClient struct {
	cc *grpc.ClientConn
}

func NewSendMessageClient(cc *grpc.ClientConn) SendMessageClient {
	return &sendMessageClient{cc}
}

func (c *sendMessageClient) SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailReply, error) {
	out := new(EmailReply)
	err := c.cc.Invoke(ctx, "/pb.SendMessage/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendMessageClient) SendCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeReply, error) {
	out := new(CodeReply)
	err := c.cc.Invoke(ctx, "/pb.SendMessage/SendCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendMessageServer is the server API for SendMessage service.
type SendMessageServer interface {
	// Sends a greeting
	SendEmail(context.Context, *EmailRequest) (*EmailReply, error)
	SendCode(context.Context, *CodeRequest) (*CodeReply, error)
}

// UnimplementedSendMessageServer can be embedded to have forward compatible implementations.
type UnimplementedSendMessageServer struct {
}

func (*UnimplementedSendMessageServer) SendEmail(ctx context.Context, req *EmailRequest) (*EmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (*UnimplementedSendMessageServer) SendCode(ctx context.Context, req *CodeRequest) (*CodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCode not implemented")
}

func RegisterSendMessageServer(s *grpc.Server, srv SendMessageServer) {
	s.RegisterService(&_SendMessage_serviceDesc, srv)
}

func _SendMessage_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMessageServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SendMessage/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMessageServer).SendEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendMessage_SendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMessageServer).SendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SendMessage/SendCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMessageServer).SendCode(ctx, req.(*CodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendMessage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SendMessage",
	HandlerType: (*SendMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _SendMessage_SendEmail_Handler,
		},
		{
			MethodName: "SendCode",
			Handler:    _SendMessage_SendCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sendmessage.proto",
}
