dependence:
	@echo "\033[32mInstalling dependence\033[0m"
	@npm install apidoc --global
	@go get github.com/kardianos/govendor
	@go get github.com/json-iterator/go
	@go get github.com/pilu/fresh
	@govendor sync

.PHONY: dependence
