basePath: /api/v1
host: 127.0.0.1:8080
info:
  contact:
    email: 2637309949@qq.com
    name: bulrush-template
    url: https://github.com/2637309949/bulrush
  description: bulrush web library template
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/2637309949/bulrush
  title: bulrush-template api
  version: "1.0"
paths:
  /chache:
    get:
      consumes:
      - multipart/form-data
      description: 测试缓存路由
      parameters:
      - description: 令牌
        in: query
        name: accessToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "ok"}'
          schema:
            type: string
        "400":
          description: '{"message": "failure"}'
          schema:
            type: string
      summary: 缓存路由
      tags:
      - Cache
  /mgoTest:
    get:
      consumes:
      - multipart/form-data
      description: MGO测试
      parameters:
      - description: 令牌
        in: query
        name: accessToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "ok"}'
          schema:
            type: string
        "400":
          description: '{"message": "failure"}'
          schema:
            type: string
      summary: MGO测试
      tags:
      - MGO
  /testsql:
    get:
      consumes:
      - multipart/form-data
      description: MGO测试
      parameters:
      - description: 令牌
        in: query
        name: accessToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "ok"}'
          schema:
            type: string
        "400":
          description: '{"message": "failure"}'
          schema:
            type: string
      summary: MGO测试
      tags:
      - GORM
swagger: "2.0"
